2024 site backports
pytexas/2025 pull request #4
Opened 2024-05-20 19:44 UTC by MasonEgger

Various backports and changes from the 2024 site, as well as just minor things and quality of life improvements.

2024-05-20 20:38 UTC, bradsbrown requested changes

2024-05-20 20:38 UTC, bradsbrown commented on docs/attend/virtual.md
> +1. Check-In and receive the `Conference 2024 Attendees` role
`s/2024/2025`

2024-05-22 19:17 UTC, MasonEgger commented on docs/attend/virtual.md
> +1. Check-In and receive the `Conference 2024 Attendees` role
```suggestion
1. Check-In and receive the `Conference 2025 Attendees` role
```

2024-05-22 19:46 UTC, MasonEgger commented on docs/attend/virtual.md
> +1. Check-In and receive the `Conference 2024 Attendees` role
Fixed.

2024-05-22 20:01 UTC, bradsbrown approved these changes

2024-05-23 17:03 UTC, merged